# Generated by Django 5.0.6 on 2024-07-28 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='descripcion_de_solicitud',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='fecha_de_entrega',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='fecha_de_salida',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='id_empleado',
        ),
        migrations.RemoveField(
            model_name='solicitudbien',
            name='id_bien',
        ),
        migrations.RemoveField(
            model_name='solicitudbien',
            name='id_solicitud',
        ),
        migrations.AddField(
            model_name='empleado',
            name='es_jefe_bienes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empleado',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='descripcion_solicitud',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='aplicacion.empleado'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='motivo_rechazo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solicitudbien',
            name='bien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.bien'),
        ),
        migrations.AddField(
            model_name='solicitudbien',
            name='descripcion_bien',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='solicitudbien',
            name='solicitud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bienes_solicitados', to='aplicacion.solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado_solicitud',
            field=models.CharField(choices=[('en_revision', 'En Revisión'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='en_revision', max_length=11),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_procesamiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudbien',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='aplicacion.empleado')),
            ],
        ),
    ]
