# Generated by Django 5.0.6 on 2024-07-31 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_remove_solicitud_descripcion_de_solicitud_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resguardo',
            old_name='id_bien',
            new_name='bien',
        ),
        migrations.RemoveField(
            model_name='bien',
            name='destino_final',
        ),
        migrations.RemoveField(
            model_name='bien',
            name='esta_archivado',
        ),
        migrations.AddField(
            model_name='resguardo',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resguardos', to='aplicacion.solicitud'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='departamento_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_destino', to='aplicacion.departamento'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_aprobacion_local',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_aprobacion_nacional',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_revision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado_solicitud',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('en_resguardo', 'En Resguardo'), ('desincorporado', 'Desincorporado')], default='pendiente', max_length=20),
        ),
        migrations.DeleteModel(
            name='ProcesoDesincorporacion',
        ),
    ]
